### ISSUE TITLE
Last version v1.7.0 not valid sample file/directory

### ISSUE THREAD

**Issue by Jazb** [clusterfrak-dynamics/teks#3]
In the last version release no more time ago, the sample directory and files no compatible with the latest changes and improvement does to code.

Addition the last version of terragrunt v0.18.7 it is not compatible with terraform 0.12.1 [issue](https://github.com/gruntwork-io/terragrunt/issues/466)

**Comment by ArchiFleKs** [comment]
Hi,

This is fixed, branch release-1.X is compatible with Terraform <0.12 and Terragrunt <0.19. Master is updating for terraform 0.12.

Kevin
